version: '3'

services:
  mysqldb:
    image: mysql:8.3.0
    restart: on-failure
    container_name: clipshot_db
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: very_secure_password
      MYSQL_DATABASE: clipshot
      MYSQL_PASSWORD: very_secure_password
    networks:
      - default
    volumes:
      - mysql_volume:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: .
    container_name: clipshot
    restart: on-failure
    ports:
      - "8081:8081"
    networks:
      - default
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/clipshot?createDatabaseIfNotExist=true&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true"
      - "SPRING_DATASOURCE_USERNAME=root"
      - "SPRING_DATASOURCE_PASSWORD=very_secure_password"

networks:
  default:
    driver: bridge

volumes:
  mysql_volume: