apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
data:
  SPRING_DATASOURCE_URL: amRiYzpteXNxbDovL2NsaXBzaG90OjMzMDgvY2xpcHNob3Q/Y3JlYXRlRGF0YWJhc2VJZk5vdEV4aXN0PXRydWUmemVyb0RhdGVUaW1lQmVoYXZpb3I9Y29udmVydFRvTnVsbCZ1c2VTU0w9ZmFsc2UmYWxsb3dQdWJsaWNLZXlSZXRyaWV2YWw9dHJ1ZQ==
  SPRING_DATASOURCE_USERNAME: YWRtaW4xMjM=
  SPRING_DATASOURCE_PASSWORD: YWRtaW4xMjM=
