apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
data:
  SPRING_DATASOURCE_URL: amRiYzpteXNxbDovL2NsaXBzaG90OjMzMDYvY2xpcHNob3QtcHJvY2Vzc29yP2NyZWF0ZURhdGFiYXNlSWZOb3RFeGlzdD10cnVlJnplcm9EYXRlVGltZUJlaGF2aW9yPWNvbnZlcnRUb051bGwmdXNlU1NMPWZhbHNlJmFsbG93UHVibGljS2V5UmV0cmlldmFsPXRydWU=
  SPRING_DATASOURCE_USERNAME: YWRtaW4xMjM=
  SPRING_DATASOURCE_PASSWORD: YWRtaW4xMjM=
