apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_DATABASE: Y2xpcHNob3Q=
  MYSQL_USER: YWRtaW4xMjM=
  MYSQL_ROOT_PASSWORD: YWRtaW4xMjM=
  MYSQL_PASSWORD: YWRtaW4xMjM=