apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_DATABASE: Y2xpcHNob3Q=
  MYSQL_USER: Y2xpcHNob3Q=
  MYSQL_ROOT_PASSWORD: bXVkYXIxMjM=
  MYSQL_PASSWORD: bXVkYXIxMjM=